serverAddr = "47.121.27.159"
serverPort = 7000

auth.token = "ljy_nb666"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

[[proxies]]
name = "lm studio"
type = "tcp"
localIP = "127.0.0.1"
localPort = 1234
remotePort = 8888

[[proxies]]
name = "512 luntan"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5230
remotePort = 9624

[[proxies]]
name = "网盘"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8198
remotePort = 8198

[[proxies]]
name = "yolo-service"
type = "tcp"
localIP = "127.0.0.1"
localPort = 9300
remotePort = 9300

[[proxies]]
name = "video-service"
type = "tcp"
localIP = "127.0.0.1"
localPort = 9400
remotePort = 9400

[[proxies]]
name = "fall-service"
type = "tcp"
localIP = "127.0.0.1"
localPort = 9500
remotePort = 9500

# [[proxies]]
# name = "xsj frontend"
# type = "tcp"
# localIP = "127.0.0.1"
# localPort = 90
# remotePort = 90

# [[proxies]]
# name = "xsj backend"
# type = "tcp"
# localIP = "127.0.0.1"
# localPort = 8089
# remotePort = 8089


